# Generated by Django 3.0.5 on 2021-05-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmPickUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Phone', models.IntegerField()),
                ('Pin', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Buyer', models.CharField(max_length=100)),
            ],
        ),
    ]
