# Generated by Django 3.0.5 on 2021-05-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_confirmpickup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('img', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('seller', models.CharField(max_length=100)),
                ('buyer', models.CharField(max_length=100)),
            ],
        ),
    ]
