# Generated by Django 3.0.5 on 2021-05-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('img', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('seller', models.CharField(max_length=100)),
                ('buyer', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
